{
 "title": "Timeseries",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "C" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  m.poll_start_ts AS \"time\",\n  t.tag_name,\n  m.temperature\nFROM measurements m\nINNER JOIN tags t on m.mac = t.mac\nWHERE\n  $__timeFilter(poll_start_ts)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  m.poll_start_ts AS \"time\",\n  t.tag_name,\n  m.humidity * 100 as humidity\nFROM measurements m\nINNER JOIN tags t on m.mac = t.mac\nWHERE\n  $__timeFilter(poll_start_ts)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  m.poll_start_ts AS \"time\",\n  t.tag_name,\n  m.pressure\nFROM measurements m\nINNER JOIN tags t on m.mac = t.mac\nWHERE\n  $__timeFilter(poll_start_ts)\nORDER BY 1"
    }
   ]
  }
 ]
}